[Fragment]
# config.toml（标准格式）
# 归一化设置
date_norm = "False"     # "False" 不进行归一化，"True" 进行归一化
Max_date = "True"       # "MAX" 理论完美匹配的得分，"True" 实际最大匹配的得分
# DNA 相关参数
A_dna = 25              # 20-30，基准窗口常数
J_dna = 0.22            # 0.15-0.35，谨慎程度
B_dna = -8              # -3 至 -10，补偿强度
C_dna = 200             # 150-300，补偿饱和点
# 蛋白质相关参数
A_protein = 15          # 12-18，基准窗口常数
J_protein = 0.28        # 0.15-0.35，谨慎程度
B_protein = -5          # -3 至 -10，补偿强度
C_protein = 100         # 50-150，补偿饱和点
# 图像显示设置
figs = "False"          # "False" 或 "True"，图像显示时是否使用真实比例
min_prop = "True"       # "False" 或 "True"，图像显示时是否限制下限
min_props = 0           # min_prop="True" 时，下限为多少
# 矩阵选择
Matrix_dna = "BLASTN"           # 选择DNA矩阵："BLASTN"、"TRANS"、"NUC.4.2"
Matrix_protein = "PAM250"       # 选择蛋白质矩阵："BLOSUM62"、"BLOSUM80"、"BLOSUM30"、"PAM250"、"PAM120"、"PAM30"
# 标签分割设置
show_leng_dna = 500             # 设置DNA标签的分割长度
show_leng_protein = 100         # 设置蛋白质标签的分割长度
# 输入输出文件设置
date_1 = "1.pep"
date_2 = "2.pep"
out_part_date_1 = "1.2pep_seq"
out_part_date_2 = "1.2pep_sco"
out_part_date_3 = "1.2pep_pro"
savefile = "output_pep.png"